######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 19 15:44:19 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

unix {
	CONFIG += link_pkgconfig
	PKGCONFIG += libusb-1.0
}

# Input
HEADERS += src/PalmSecure.hpp src/QUsb.hpp src/QUsbDevice.hpp
SOURCES += src/cli.cpp src/PalmSecure.cpp src/QUsb.cpp src/QUsbDevice.cpp
